repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.85.0
  hooks:
    - id: terraform_tflint
      args:
      - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    - id: terraform_docs
      args:
      - --hook-config=--create-file-if-not-exist=true
    - id: terraform_fmt
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
